# Generated by Django 5.2.15 on 2026-06-06 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_uzs', models.PositiveIntegerField(default=0)),
                ('package_orders_remaining', models.PositiveIntegerField(default=0)),
                ('free_orders_remaining', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='masters.masterprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MasterLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('manual_top_up', 'Manual top-up'), ('package_purchase', 'Package purchase'), ('order_debit', 'Order debit'), ('adjustment', 'Adjustment')], max_length=32)),
                ('amount_uzs', models.IntegerField()),
                ('balance_after_uzs', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='billing.masterwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
